In [1]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
%matplotlib qt

1.
Implementar el algoritmo de pasaje a coordenadas cromáticas para librarnos de las variaciones de contraste.

In [2]:
img_cc_1_BGR = cv.imread('CoordCrom_1.png')
img_cc_1_RGB = cv.cvtColor(img_cc_1_BGR, cv.COLOR_BGR2RGB)
plt.imshow(img_cc_1_RGB)
plt.show()

In [3]:
img_cc_2_BGR = cv.imread('CoordCrom_2.png')
img_cc_2_RGB = cv.cvtColor(img_cc_2_BGR, cv.COLOR_BGR2RGB)
plt.imshow(img_cc_2_RGB)
plt.show()

In [4]:
img_cc_3_BGR = cv.imread('CoordCrom_3.png')
img_cc_3_RGB = cv.cvtColor(img_cc_3_BGR, cv.COLOR_BGR2RGB)
plt.imshow(img_cc_3_RGB)
plt.show()

In [5]:
sumaRGB_cc1= np.sum(img_cc_1_RGB, axis=2, keepdims= True)
sumaRGB_cc2= np.sum(img_cc_2_RGB, axis=2, keepdims= True)
sumaRGB_cc3= np.sum(img_cc_3_RGB, axis=2, keepdims= True)

In [6]:
sumaRGB_cc1 [sumaRGB_cc1==0]= 1
sumaRGB_cc2 [sumaRGB_cc2==0]= 1
sumaRGB_cc3 [sumaRGB_cc3==0]= 1

In [12]:
ccrom_1 = img_cc_1_RGB / sumaRGB_cc1
plt.imshow(ccrom_1)
plt.show()

In [13]:
ccrom_2 = img_cc_2_RGB / sumaRGB_cc2
plt.imshow(ccrom_2)
plt.show()

In [14]:
ccrom_3 = img_cc_3_RGB / sumaRGB_cc3
plt.imshow(ccrom_3)
plt.show()

In [10]:
#Separación de coordenadas cromáticas para la imagen 1
ccromatica_r = ccrom_1[:, :, 0]
ccromatica_g = ccrom_1[:, :, 1]
ccromatica_b = ccrom_1[:, :, 2]

2.
Implementar el algoritmo White
Patch para librarnos de las diferencias de color de iluminación.

In [27]:
#Aplicación del algoritmo a la imagen wp_r
img_r = cv.imread('wp_red.png')
img_r = cv.cvtColor(img_r, cv.COLOR_BGR2RGB)
plt.imshow(img_r)
plt.show()

In [62]:
r_max= np.max(img_r[:,:,0])
g_max= np.max(img_r[:,:,1])
b_max= np.max(img_r[:,:,2])
print(r_max, g_max, b_max)

255 134 122


In [17]:
scale_r = 255/r_max
scale_g = 255/g_max
scale_b = 255/b_max

In [18]:
img_r_scaled = cv.imread('wp_red.png')
img_r_scaled = cv.cvtColor(img_r_scaled, cv.COLOR_BGR2RGB)

In [19]:
img_r_scaled[:, :, 0] = img_r[:, :, 0]*scale_r
img_r_scaled[:, :, 1] = img_r[:, :, 1]*scale_g
img_r_scaled[:, :, 2] = img_r[:, :, 2]*scale_b

In [20]:
plt.imshow(img_r_scaled)
plt.show()

In [34]:
fig, axs = plt.subplots(1, 2, figsize=(8, 12))

axs[0].imshow(img_r)
axs[0].set_title('Imagen Original')

axs[1].imshow(img_r_scaled)
axs[1].set_title('Aplicando White Patch')

plt.show()

In [54]:
#Aplicación del algoritmo a la imagen wp_blue
img_b = cv.imread('wp_blue.jpg')
img_b = cv.cvtColor(img_b, cv.COLOR_BGR2RGB)
plt.imshow(img_b)
plt.show()

In [61]:
r_max= np.max(img_b[:,:,0])
g_max= np.max(img_b[:,:,1])
b_max= np.max(img_b[:,:,2])
print(r_max, g_max, b_max)

255 255 255


In [56]:
scale_r = 255/r_max
scale_g = 255/g_max
scale_b = 255/b_max

In [57]:
img_b_scaled = cv.imread('wp_blue.jpg')
img_b_scaled = cv.cvtColor(img_b_scaled, cv.COLOR_BGR2RGB)

In [58]:
img_b_scaled[:, :, 0] = img_b[:, :, 0]*scale_r
img_b_scaled[:, :, 1] = img_b[:, :, 1]*scale_g
img_b_scaled[:, :, 2] = img_b[:, :, 2]*scale_b

In [59]:
plt.imshow(img_b_scaled)
plt.show()

In [60]:
fig, axs = plt.subplots(1, 2, figsize=(8, 12))

axs[0].imshow(img_b)
axs[0].set_title('Imagen Original')

axs[1].imshow(img_b_scaled)
axs[1].set_title('Aplicando White Patch')

plt.show()

In [ ]:
# PROBLEMA CON WP: El máximo de cada canal es 255, por lo que el algoritmo no realiza transformación alguna. En cambio en wp_red,
# el único que tiene máximo en 255 es el canal rojo

In [63]:
#Aplicación del algoritmo a la imagen wp_green
img_g = cv.imread('wp_green.png')
img_g = cv.cvtColor(img_g, cv.COLOR_BGR2RGB)
plt.imshow(img_g)
plt.show()

In [64]:
r_max= np.max(img_g[:,:,0])
g_max= np.max(img_g[:,:,1])
b_max= np.max(img_g[:,:,2])
print(r_max, g_max, b_max)

126 252 155


In [65]:
scale_r = 255/r_max
scale_g = 255/g_max
scale_b = 255/b_max

In [66]:
img_g_scaled = cv.imread('wp_green.png')
img_g_scaled = cv.cvtColor(img_g_scaled, cv.COLOR_BGR2RGB)

In [67]:
img_g_scaled[:, :, 0] = img_g[:, :, 0]*scale_r
img_g_scaled[:, :, 1] = img_g[:, :, 1]*scale_g
img_g_scaled[:, :, 2] = img_g[:, :, 2]*scale_b

In [69]:
plt.imshow(img_g_scaled)
plt.show()

In [70]:
fig, axs = plt.subplots(1, 2, figsize=(8, 12))

axs[0].imshow(img_g)
axs[0].set_title('Imagen Original')

axs[1].imshow(img_g_scaled)
axs[1].set_title('Aplicando White Patch')

plt.show()

In [71]:
#Aplicación del algoritmo a la imagen wp_red2
img_r2 = cv.imread('wp_red2.jpg')
img_r2 = cv.cvtColor(img_r2, cv.COLOR_BGR2RGB)
plt.imshow(img_r2)
plt.show()

In [72]:
r_max= np.max(img_r2[:,:,0])
g_max= np.max(img_r2[:,:,1])
b_max= np.max(img_r2[:,:,2])
print(r_max, g_max, b_max)

255 201 203


In [73]:
scale_r = 255/r_max
scale_g = 255/g_max
scale_b = 255/b_max

In [74]:
img_r2_scaled = cv.imread('wp_red2.jpg')
img_r2_scaled = cv.cvtColor(img_r2_scaled, cv.COLOR_BGR2RGB)

In [75]:
img_r2_scaled[:, :, 0] = img_r2[:, :, 0]*scale_r
img_r2_scaled[:, :, 1] = img_r2[:, :, 1]*scale_g
img_r2_scaled[:, :, 2] = img_r2[:, :, 2]*scale_b

In [76]:
plt.imshow(img_r2_scaled)
plt.show()

In [81]:
fig, axs = plt.subplots(2, 2, figsize=(8, 12))

axs[0][0].imshow(img_r2)
axs[0][0].set_title('Imagen Original Red 2')

axs[0][1].imshow(img_r2_scaled)
axs[0][1].set_title('Aplicando White Patch a Red 2')

axs[1][0].imshow(img_r)
axs[1][0].set_title('Imagen Original Red')

axs[1][1].imshow(img_r_scaled)
axs[1][1].set_title('Imagen Original Red')

plt.show()

#Podemos ver que en la wp_red, los colores máximos en los canales b y g son menores, por lo que el escalado es mayor y se aprecian más detalles que en 
# el wp_red2 que tiene máximos más cercanos al 255 (255,201,203), siendo WP menos efectivo.

In [82]:
#Aplicación del algoritmo a la imagen wp_green2
img_g2 = cv.imread('wp_green2.jpg')
img_g2 = cv.cvtColor(img_g2, cv.COLOR_BGR2RGB)
plt.imshow(img_g2)
plt.show()

In [83]:
r_max= np.max(img_g2[:,:,0])
g_max= np.max(img_g2[:,:,1])
b_max= np.max(img_g2[:,:,2])
print(r_max, g_max, b_max)

170 255 172


In [84]:
scale_r = 255/r_max
scale_g = 255/g_max
scale_b = 255/b_max

In [85]:
img_g2_scaled = cv.imread('wp_green2.jpg')
img_g2_scaled = cv.cvtColor(img_g2_scaled, cv.COLOR_BGR2RGB)

In [86]:
img_g2_scaled[:, :, 0] = img_g2[:, :, 0]*scale_r
img_g2_scaled[:, :, 1] = img_g2[:, :, 1]*scale_g
img_g2_scaled[:, :, 2] = img_g2[:, :, 2]*scale_b

In [87]:
plt.imshow(img_g2_scaled)
plt.show()

In [88]:
fig, axs = plt.subplots(2, 2, figsize=(8, 12))

axs[0][0].imshow(img_g2)
axs[0][0].set_title('Imagen Original Green 2')

axs[0][1].imshow(img_g2_scaled)
axs[0][1].set_title('Aplicando White Patch a Green 2')

axs[1][0].imshow(img_g)
axs[1][0].set_title('Imagen Original Green')

axs[1][1].imshow(img_g_scaled)
axs[1][1].set_title('Imagen Original Green')

plt.show()
#Sucede lo mismo a la comparación entre wp_red y wp_red2. En este caso wp_green tiene colores máximos mucho más próximos al 255

In [89]:
#Aplicación del algoritmo WP a test_blue
img_tb = cv.imread('test_blue.png')
img_tb = cv.cvtColor(img_tb, cv.COLOR_BGR2RGB)
plt.imshow(img_tb)
plt.show()

In [94]:
r_max= np.max(img_tb[:,:,0])
g_max= np.max(img_tb[:,:,1])
b_max= np.max(img_tb[:,:,2])
print(r_max,g_max,b_max)

165 138 200


In [95]:
scale_r = 255/r_max
scale_g = 255/g_max
scale_b = 255/b_max

In [96]:
img_tb_scaled = cv.imread('test_blue.png')
img_tb_scaled = cv.cvtColor(img_tb, cv.COLOR_BGR2RGB)

In [97]:
img_tb_scaled[:, :, 0] = img_tb[:, :, 0]*scale_r
img_tb_scaled[:, :, 1] = img_tb[:, :, 1]*scale_g
img_tb_scaled[:, :, 2] = img_tb[:, :, 2]*scale_b

In [98]:
plt.imshow(img_tb_scaled)
plt.show()

In [99]:
fig, axs = plt.subplots(1, 2, figsize=(8, 12))

axs[0].imshow(img_tb)
axs[0].set_title('Imagen Original')

axs[1].imshow(img_tb_scaled)
axs[1].set_title('Aplicando White Patch')

plt.show()

In [101]:
#Aplicación del algoritmo WP a test_green
img_tg = cv.imread('test_green.png')
img_tg = cv.cvtColor(img_tg, cv.COLOR_BGR2RGB)
plt.imshow(img_tg)
plt.show()

In [102]:
r_max= np.max(img_tg[:,:,0])
g_max= np.max(img_tg[:,:,1])
b_max= np.max(img_tg[:,:,2])
print(r_max,g_max,b_max)

210 250 171


In [103]:
scale_r = 255/r_max
scale_g = 255/g_max
scale_b = 255/b_max

In [104]:
img_tg_scaled = cv.imread('test_green.png')
img_tg_scaled = cv.cvtColor(img_tg, cv.COLOR_BGR2RGB)

In [105]:
img_tg_scaled[:, :, 0] = img_tg[:, :, 0]*scale_r
img_tg_scaled[:, :, 1] = img_tg[:, :, 1]*scale_g
img_tg_scaled[:, :, 2] = img_tg[:, :, 2]*scale_b

In [106]:
plt.imshow(img_tg_scaled)
plt.show()

In [107]:
fig, axs = plt.subplots(1, 2, figsize=(8, 12))

axs[0].imshow(img_tg)
axs[0].set_title('Imagen Original')

axs[1].imshow(img_tg_scaled)
axs[1].set_title('Aplicando White Patch')

plt.show()

In [108]:
#Aplicación del algoritmo WP a test_red
img_tr = cv.imread('test_red.png')
img_tr = cv.cvtColor(img_tr, cv.COLOR_BGR2RGB)
plt.imshow(img_tr)
plt.show()

In [109]:
r_max= np.max(img_tr[:,:,0])
g_max= np.max(img_tr[:,:,1])
b_max= np.max(img_tr[:,:,2])
print(r_max,g_max,b_max)

247 157 175


In [110]:
scale_r = 255/r_max
scale_g = 255/g_max
scale_b = 255/b_max

In [111]:
img_tr_scaled = cv.imread('test_red.png')
img_tr_scaled = cv.cvtColor(img_tr, cv.COLOR_BGR2RGB)

In [112]:
img_tr_scaled[:, :, 0] = img_tr[:, :, 0]*scale_r
img_tr_scaled[:, :, 1] = img_tr[:, :, 1]*scale_g
img_tr_scaled[:, :, 2] = img_tr[:, :, 2]*scale_b

In [113]:
plt.imshow(img_tr_scaled)
plt.show()

In [114]:
fig, axs = plt.subplots(1, 2, figsize=(8, 12))

axs[0].imshow(img_tr)
axs[0].set_title('Imagen Original')

axs[1].imshow(img_tr_scaled)
axs[1].set_title('Aplicando White Patch')

plt.show()

1.
Para las imágenes
img1_tp.png y img2_tp.png leerlas con OpenCV en escala de grisas y visualizarla
2. Elija el numero de
bins que crea conveniente y grafique su histograma, compare los histogramas entre si.
Explicar lo que se observa, si tuviera que entrenar un modelo de clasificación/detección de imágenes,
considera que puede ser de utilidad tomar como ‘ features ’ a loss.

In [118]:
img_1 = cv.imread('img1_tp.png', cv.IMREAD_GRAYSCALE)
img_1 = cv.cvtColor(img_1, cv.COLOR_BGR2RGB)
plt.imshow(img_1)
plt.show()

In [119]:
img_2 = cv.imread('img2_tp.png', cv.IMREAD_GRAYSCALE)
img_2 = cv.cvtColor(img_2, cv.COLOR_BGR2RGB)
plt.imshow(img_2)
plt.show()

In [203]:
fig = plt.figure()
hist1, bins1 = np.histogram(img_1.ravel(), 256, [0, 256])
plt.plot(hist1) 
plt.show()

In [121]:
fig = plt.figure()
hist2, bins2 = np.histogram(img_2.ravel(), 256, [0, 256])
plt.plot(hist2)
plt.show()

In [124]:
# Estuve más de 15 minutos viendo el código ya que ambos histogramas son iguales y quería saber si tengo algún error, pero por lo que
# veo, siendo imágenes tan diferentes, tienen la misma distribución. Teniendo la misma distribución no podrían ser utilizados como features
# para un problema de clasificación.
#Lo que se ve en los histogramas es saturación de blancos por la alta frecuencia en 255

3. Para la imagen
segmentacion.png analice el histograma de los canales RGB. Segmente algunos de los
elementos presentes en la imagen (agua, cielo, tierra) y muestre, aplicando mascaras, las regiones en imágenes
separadatado

In [152]:
img_seg = cv.imread('segmentacion.png')
img_seg = cv.cvtColor(img_seg, cv.COLOR_BGR2RGB)
plt.imshow(img_seg)
plt.show()
print(img_seg.shape)

(628, 953, 3)


In [142]:
plt.figure()
hist_r,_=np.histogram(img_seg[:,:,0].ravel(), 256, [0,256])
hist_g,_=np.histogram(img_seg[:,:,1].ravel(), 256, [0,256])
hist_b,_=np.histogram(img_seg[:,:,2].ravel(), 256, [0,256])
plt.plot(hist_r, color='red', label='Rojo')
plt.plot(hist_g, color='green', label='Verde')
plt.plot(hist_b, color='blue', label='Azul')
plt.show()
#El color rojo tiene sesgo a derecha (altas frecuencias con intensidad baja y muy pocas con alta intensidad), por lo que casi no impacta en la imagen. 
# El verde es simétrico, mientras que el azul es sesgado a izquierda, con alta intensidad, dadas por parte del mar y del cielo.

In [144]:
hist = cv.calcHist([img_seg], channels=[0, 1], mask=None, histSize=[256, 256], ranges=[0, 255, 0, 255])
plt.figure()
plt.imshow(hist, cmap='jet')
plt.show()
#Viendo el historgrama en 2D de rojo y verde, vemos que existe una correlación positiva bastante marcada hasta la intensidad aproximada de 150, que se corresponde
# con los histogramas 1D. Luego, el rojo disminuye y el verde aumenta, por lo que la correlación cambia su pendiente, y se hace menos marcada.

In [145]:
hist = cv.calcHist([img_seg], channels=[1, 2], mask=None, histSize=[256, 256], ranges=[0, 255, 0, 255])
plt.figure()
plt.imshow(hist, cmap='jet')
plt.show()

#Correlación débil entre verde y azul en las intensidades bajas, luego cambia de pendiente.

In [146]:
hist = cv.calcHist([img_seg], channels=[0, 2], mask=None, histSize=[256, 256], ranges=[0, 255, 0, 255])
plt.figure()
plt.imshow(hist, cmap='jet')
plt.show()
#Solo hay correlación en las primeras intensidades cerca del 0, luego ya no existe casi correlación

In [147]:
img_muestra_montaña = img_seg[450:600, 450:600,:]
plt.figure(2)
plt.imshow(img_muestra_montaña)
plt.show()

In [150]:
color_mean, color_std = cv.meanStdDev(img_muestra_montaña)
print(color_mean)
print(color_std)

[[68.27231111]
 [54.27884444]
 [35.21173333]]
[[50.22842955]
 [44.62724157]
 [34.13637441]]


In [151]:
n_sigma = 1
mask = cv.inRange(img_seg, color_mean-color_std * n_sigma,  color_mean+color_std * n_sigma)
img_segmentada_montaña = cv.bitwise_and(img_seg, img_seg, mask=mask)

plt.figure(3)
plt.imshow(img_segmentada_montaña)
plt.show()

In [ ]:
# Hay que ponerle 1 sigma ya que con más sigmas toma parte de la playa. Para mí, es porque la media y la desv estándar están en los
# mismos órdenes de magnitud, por lo que agranda mucho el rango de colores que toma y pasa del marrón al azul.

In [158]:
img_seg.shape

(628, 953, 3)

In [182]:
img_muestra_cielo = img_seg[0:200,220:750,:]
plt.figure(2)
plt.imshow(img_muestra_cielo)
plt.show()

In [183]:
color_mean, color_std = cv.meanStdDev(img_muestra_cielo)
print(color_mean)
print(color_std)

[[ 47.54386792]
 [144.78648113]
 [217.34075472]]
[[54.35582366]
 [23.66480597]
 [11.0753227 ]]


In [184]:
n_sigma = 3.3
mask = cv.inRange(img_seg, color_mean-color_std * n_sigma,  color_mean+color_std * n_sigma)
img_segmentada_cielo = cv.bitwise_and(img_seg, img_seg, mask=mask)

plt.figure(3)
plt.imshow(img_segmentada_cielo)
plt.show()
#Varié la std desde 1 hasta 3.3. Con 1 y 2 toma muy poco del cielo. Con 2.5 deja una mancha negra a la derecha que se corresponde con los blancos.
#Subiendo a 3, toma casi todos los blancos del cielo pero comienza a tomar los blancos de la espuma del mar. con 3.3 de std toma todo el cielo y
#no varía casi la espuma del mar.


In [175]:
img_muestra_cielo = img_seg[0:230,100:800,:]
plt.figure(2)
plt.imshow(img_muestra_cielo)
plt.show()

In [176]:
color_mean, color_std = cv.meanStdDev(img_muestra_cielo)
print(color_mean)
print(color_std)

[[ 49.60285714]
 [145.34484472]
 [215.80992547]]
[[53.05960627]
 [24.69724558]
 [12.52074337]]


In [181]:
n_sigma = 3
mask = cv.inRange(img_seg, color_mean-color_std * n_sigma,  color_mean+color_std * n_sigma)
img_segmentada_cielo = cv.bitwise_and(img_seg, img_seg, mask=mask)

plt.figure(3)
plt.imshow(img_segmentada_cielo)
plt.show()

#Aumentando la región de muestra no da un resultado significativamente diferente

In [185]:
img_muestra_mar = img_seg[280:420,400:500,:]
plt.figure(2)
plt.imshow(img_muestra_mar)
plt.show()

In [186]:
color_mean, color_std = cv.meanStdDev(img_muestra_mar)
print(color_mean)
print(color_std)

[[ 93.5285    ]
 [124.46535714]
 [134.87357143]]
[[67.37551199]
 [51.63754116]
 [50.47236459]]


In [202]:
n_sigma = 1.5
mask = cv.inRange(img_seg, color_mean-1.5*color_std * n_sigma,  color_mean+color_std * 0.5*n_sigma)
img_segmentada_mar = cv.bitwise_and(img_seg, img_seg, mask=mask)

plt.figure(3)
plt.imshow(img_segmentada_mar)
plt.show()

#Sucede algo similar con la segmentación de cielo, se mezclan los colores. La std debe ser como máximo 2 ya que ocn tres toma casi toda la imagen
#al tener la muestra partes marrones de la costa, que con 3std toman la montaña
#Si coloco diferentes sigmas para el limite superior e inferior, obtengo una mejor segmentación de la parte azul, pero falta la parte blanca
# de la espuma de las olas. Si aumento el sigma superior, comienza a tomar el color azul claro del cielo.